### ISSUE TITLE
Android 项目升级API28 问题记录

### ISSUE THREAD

**Issue by ythy** [ythy/blog#526]
> 环境目录
1.  Gradle - version 5.1.1
2.  Android Gradle plugin - version 3.4.1
3.  Android SDK Build Tools - version  28.0.3

参考：
```bash
To take advantage of the latest features, improvements, and security fixes, 
we strongly recommend that you update the Android Gradle plugin to version 3.4.1 and Gradle to version 5.1.1.

Release notes Android plugin 3.2.0 and higher now support building the Android App Bundle—a new upload format that defers APK generation and signing to compatible app stores, such as Google Play. With app bundles, you no longer have to build, sign, and manage multiple APKs, and users get smaller, more optimized downloads. 

WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
```

#### 依赖下载不能，增加代理
```gradle
repositories {
    maven {
        url 'https://maven.aliyun.com/repository/public/'
    }
    maven {
        url 'https://maven.aliyun.com/repository/central'
    }
    maven {
        url 'https://maven.aliyun.com/repository/gradle-plugin'
    }
    mavenCentral()
    maven{ url 'https://maven.aliyun.com/repository/google'}
    google()
}
```
#### org.apache.http 找不到
增加2项依赖：
```gradle
 implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.14'
 implementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.16'
```
#### Notification.setLatestEventInfo 弃用
 1.  新增权限  `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`
 2. 
#### FloatMath.sqrt  API23 弃用
用`(float) Math.sqrt()` 替代
#### Android10 以上无法获取 IMEI 
无法处理，需要更改业务逻辑
#### Cleartext HTTP traffic to xx.xx.xx.xx not permitted
API28 要求HTTPS加密传输

#### 文件目录读取方式替换
替换为 `this.getBaseContext().getExternalFilesDir("")`,    否则用旧方式`Environment.getExternalStorageDirectory()`无法静默创建文件
#### 打开APK的方式变更
as-is:
```java
  Intent intent =  new Intent(Intent.ACTION_VIEW); 
  intent.addCategory("android.intent.category.DEFAULT"); 
  intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK); 
  intent.setDataAndType(uri, "application/vnd.android.package-archive"); 
  startActivity(intent);
```
This works great for all the device < 24
Now with Android 24 apparently we are not allowed any more to start intents with file:/// and after some googling it was advised to use A File Provider

You also need to add the permission *REQUEST_INSTALL_PACKAGES*  in your manifest. Its available from Api Level 23 (Android 6.0 Marshmallow) and required from Level 25 (Android 7.1 Nougat).

重点来了，如何构造FileProvider
1.  写一个path文件，放到`res/xml`目录,  
     `external-path` represents files in the root of your app's external storage area. The path `Context.getExternalFilesDir()` returns the `files/` subdirectory of this this root.
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
<paths>
    <external-path
        name="apk_files"
        path="" />
    <root-path
        name="apk_files"
        path="" />
</paths>
</resources>
```
2.  `AndroidManifest.xml`文件里增加`Provider`, 指向刚才新建的path文件
```xml
<application
        android:name=".application.BasedApplication"
        android:icon="@drawable/icon"
        android:label="@string/app_name"
        tools:ignore="GoogleAppIndexingWarning">
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.mx.android.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_provider_paths" />
        </provider>
</application>

```

3.  最终使用
```java
Uri apkUri = FileProvider.getUriForFile(UpdateService.this, "com.mx.android.fileprovider", File);
								Intent intent = new Intent(Intent.ACTION_INSTALL_PACKAGE);
								intent.setData(apkUri);
								intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_ACTIVITY_NEW_TASK);
								startActivity(intent);
```

**Comment by ythy** [comment]
```bash
2023-10-31 15:26:46.526 24156-24156/com.imc.android W/System.err: java.io.FileNotFoundException: /data/user/0/com.imc.android/files/login_userId_auto: open failed: ENOENT (No such file or directory)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:160)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.ContextImpl.openFileInput(ContextImpl.java:673)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:226)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at com.imc.android.common.util.CommonUtil.getAutoList(CommonUtil.java:69)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at com.imc.android.activity.home.LoginActivity.onCreate(LoginActivity.java:87)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.Activity.performCreate(Activity.java:8207)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.Activity.performCreate(Activity.java:8191)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.os.Looper.loop(Looper.java:246)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8653)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2023-10-31 15:26:46.528 24156-24156/com.imc.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err:     at libcore.io.Linux.open(Native Method)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8514)
2023-10-31 15:26:46.529 24156-24156/com.imc.android W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:478)



D/MP UPDATA: /storage/emulated/0/Android/data/com.imc.android/download ; /storage/emulated/0/Android/data/com.imc.android/download/MP.apk

2023-10-31 15:26:50.467 24156-3504/com.imc.android W/System.err: java.io.IOException: No such file or directory
2023-10-31 15:26:50.469 24156-3504/com.imc.android W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2023-10-31 15:26:50.469 24156-3504/com.imc.android W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
2023-10-31 15:26:50.469 24156-3504/com.imc.android W/System.err:     at java.io.File.createNewFile(File.java:1008)
2023-10-31 15:26:50.469 24156-3504/com.imc.android W/System.err:     at com.imc.android.service.UpdateService$updateRunnable.run(UpdateService.java:155)
2023-10-31 15:26:50.469 24156-3504/com.imc.android W/System.err:     at java.lang.Thread.run(Thread.java:923)




2023-11-01 08:54:00.765 3871-19923/com.imc.android I/AlertDialog: null  com.imc.android.activity.home.LoginActivity  main getMessage: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=file:///storage/emulated/0/Android/data/com.imc.android/files/download/MP.apk typ=application/vnd.android.package-archive flg=0x10000000 }

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
        at com.imc.android.service.UpdateService.onStartCommand(UpdateService.java:64)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4795)
        at android.app.ActivityThread.access$2000(ActivityThread.java:301) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 


  --------- beginning of crash
2023-11-01 14:43:31.751 4642-4642/com.imc.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imc.android, PID: 4642
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:243)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:217)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:130)
        at com.imc.android.service.UpdateService$1$1.onClick(UpdateService.java:126)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:188)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2023-11-01 14:43:31.758 4642-8982/com.imc.android I/AlertDialog: null  com.imc.android.activity.home.LoginActivity  main getMessage: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
2023-11-01 14:43:31.759 4642-8982/com.imc.android I/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2023-11-01 14:43:31.763 4642-8982/com.imc.android I/DecorView: [INFO] isPopOver=false, config=false
2023-11-01 14:43:31.763 4642-8982/com.imc.android I/DecorView: updateCaptionType >> DecorView@1f21a7d[], isFloating=true, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=false
2023-11-01 14:43:31.763 4642-8982/com.imc.android D/DecorView: setCaptionType = 0, this = DecorView@1f21a7d[]
2023-11-01 14:43:31.777 4642-8982/com.imc.android D/ScrollView: initGoToTop
2023-11-01 14:43:31.802 4642-8982/com.imc.android D/InputTransport: Input channel constructed: '6ca1315', fd=79
2023-11-01 14:43:31.802 4642-8983/com.imc.android I/HttpServiceUtil:  request: {"sActivityName":"com.imc.android.activity.home.LoginActivity","sErrorInfo":"Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference","versionNo":"209","versionSize":0}
2023-11-01 14:43:31.803 4642-8982/com.imc.android I/ViewRootImpl@ab29b5d[LoginActivity]: setView = com.android.internal.policy.DecorView@1f21a7d TM=true
2023-11-01 14:43:31.806 4642-8983/com.imc.android I/System.out: Thread-1644(ApacheHTTPLog):Reading from variable values from setDefaultValuesToVariables
2023-11-01 14:43:31.806 4642-8983/com.imc.android I/System.out: Thread-1644(ApacheHTTPLog):isSBSettingEnabled false
2023-11-01 14:43:31.806 4642-8983/com.imc.android I/System.out: Thread-1644(ApacheHTTPLog):isShipBuild true
2023-11-01 14:43:31.806 4642-8983/com.imc.android I/System.out: Thread-1644(ApacheHTTPLog):getDebugLevel 0x4f4c
2023-11-01 14:43:31.806 4642-8983/com.imc.android I/System.out: Thread-1644(ApacheHTTPLog):Smart Bonding Setting is false
2023-11-01 14:43:31.806 4642-8983/com.imc.android I/System.out: Thread-1644(ApacheHTTPLog):SmartBonding Setting is false, SHIP_BUILD is true, log to file is false, DBG is false, DEBUG_LEVEL (1-LOW, 2-MID, 3-HIGH) is 1
2023-11-01 14:43:31.837 4642-8982/com.imc.android I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x17664f7 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1836 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995
2023-11-01 14:43:31.839 4642-8982/com.imc.android I/ViewRootImpl@ab29b5d[LoginActivity]: Relayout returned: old=(0,112,1080,2214) new=(146,835,934,1173) req=(788,338)0 dur=8 res=0x100007 s={true 519846726496} ch=true fn=-1
2023-11-01 14:43:31.849 4642-8982/com.imc.android I/SurfaceControl: nativeRelease nativeObject s[515551871984]
2023-11-01 14:43:31.849 4642-8982/com.imc.android I/SurfaceControl: nativeRelease nativeObject e[515551871984]
2023-11-01 14:43:31.849 4642-8982/com.imc.android I/SurfaceControl: nativeRelease nativeObject s[515551881136]
2023-11-01 14:43:31.849 4642-8982/com.imc.android I/SurfaceControl: nativeRelease nativeObject e[515551881136]
2023-11-01 14:43:31.861 4642-8982/com.imc.android I/ViewRootImpl@ab29b5d[LoginActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2023-11-01 14:43:31.891 4642-8983/com.imc.android I/System.out: Thread-8 calls detatch()
2023-11-01 14:43:31.891 4642-8983/com.imc.android D/HttpServiceUtil: response:  {"data":"保存成功","error":false,"msg":"保存成功"}






2023-11-01 16:16:39.306 5902-5902/com.imc.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imc.android, PID: 5902
    java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.imc.android/files/download/MP.apk
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:361)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:131)
        at com.imc.android.service.UpdateService$1$1.onClick(UpdateService.java:126)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:188)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2023-11-01 16:16:39.307 5902-22133/com.imc.android I/AlertDialog: null  com.imc.android.activity.home.LoginActivity  main getMessage: Failed to find configured root that contains /storage/emulated/0/Android/data/com.imc.android/files/download/MP.apk
2023-11-01 16:16:39.309 5902-22133/com.imc.android I/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2023-11-01 16:16:39.315 5902-22133/com.imc.android I/DecorView: [INFO] isPopOver=false, config=false
2023-11-01 16:16:39.315 5902-22133/com.imc.android I/DecorView: updateCaptionType >> DecorView@8075b1f[], isFloating=true, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=false
2023-11-01 16:16:39.315 5902-22133/com.imc.android D/DecorView: setCaptionType = 0, this = DecorView@8075b1f[]
2023-11-01 16:16:39.329 5902-22133/com.imc.android D/ScrollView: initGoToTop
2023-11-01 16:16:39.352 5902-22133/com.imc.android D/InputTransport: Input channel constructed: 'aea69fc', fd=80
2023-11-01 16:16:39.353 5902-22133/com.imc.android I/ViewRootImpl@1829059[LoginActivity]: setView = com.android.internal.policy.DecorView@8075b1f TM=true
2023-11-01 16:16:39.354 5902-22136/com.imc.android I/HttpServiceUtil:  request: {"sActivityName":"com.imc.android.activity.home.LoginActivity","sErrorInfo":"Failed to find configured root that contains \/storage\/emulated\/0\/Android\/data\/com.imc.android\/files\/download\/MP.apk","versionNo":"209","versionSize":0}
2023-11-01 16:16:39.359 5902-22136/com.imc.android I/System.out: Thread-1700(ApacheHTTPLog):Reading from variable values from setDefaultValuesToVariables
2023-11-01 16:16:39.359 5902-22136/com.imc.android I/System.out: Thread-1700(ApacheHTTPLog):isSBSettingEnabled false
2023-11-01 16:16:39.359 5902-22136/com.imc.android I/System.out: Thread-1700(ApacheHTTPLog):isShipBuild true
2023-11-01 16:16:39.359 5902-22136/com.imc.android I/System.out: Thread-1700(ApacheHTTPLog):getDebugLevel 0x4f4c
2023-11-01 16:16:39.360 5902-22136/com.imc.android I/System.out: Thread-1700(ApacheHTTPLog):Smart Bonding Setting is false
2023-11-01 16:16:39.360 5902-22136/com.imc.android I/System.out: Thread-1700(ApacheHTTPLog):SmartBonding Setting is false, SHIP_BUILD is true, log to file is false, DBG is false, DEBUG_LEVEL (1-LOW, 2-MID, 3-HIGH) is 1
2023-11-01 16:16:39.376 5902-22133/com.imc.android I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0xb225993 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1836 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995
2023-11-01 16:16:39.379 5902-22133/com.imc.android I/ViewRootImpl@1829059[LoginActivity]: Relayout returned: old=(0,112,1080,2214) new=(146,835,934,1173) req=(788,338)0 dur=8 res=0x100007 s={true 519846743936} ch=true fn=-1
2023-11-01 16:16:39.389 5902-22133/com.imc.android I/SurfaceControl: nativeRelease nativeObject s[515551877264]
2023-11-01 16:16:39.389 5902-22133/com.imc.android I/SurfaceControl: nativeRelease nativeObject e[515551877264]
2023-11-01 16:16:39.389 5902-22133/com.imc.android I/SurfaceControl: nativeRelease nativeObject s[515551880608]
2023-11-01 16:16:39.389 5902-22133/com.imc.android I/SurfaceControl: nativeRelease nativeObject e[515551880608]
2023-11-01 16:16:39.395 5902-22133/com.imc.android I/ViewRootImpl@1829059[LoginActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2023-11-01 16:16:39.433 5902-22136/com.imc.android I/System.out: Thread-8 calls detatch()
2023-11-01 16:16:39.434 5902-22136/com.imc.android D/HttpServiceUtil: response:  {"data":"保存成功","error":false,"msg":"保存成功"}
```
